<?php

/**
 * @file
 * recipe_html.module - Enables importing and exporting of full-page html recipes.
 */

/**
 * Implementation of hook_recipeio($type).
 */
function recipe_html_recipeio($type) {
  $supported = array(
    'export_single' => array(
      'format_name' => t('HTML'),
      'callback' => 'recipe_html_export_single',
      'format_help' => t('Export to a printer friendly HTML format.'),
      'access arguments' => 'access content',   // everyone should be able to export HTML
    )
  );

  if ( isset($supported[$type]) ) {
    return array('reciphtml' => $supported[$type]);
  }
  else {
    return FALSE;
  }
}

/**
 * Example implementation of hook_perm().  If you need special permissions for a format,
 * use this and match the permission name to the access arguments above.

function recipe_html_perm() {
  return array(t('export single'));
}
*/


function recipe_html_export_single($nid = NULL, $yield = NULL) {
  if ( $nid === NULL ) {
    drupal_set_message(t('Recipe not found.'));
    drupal_not_found();
    return;
  }
  $node = node_load($nid);

  // Set the custom yield so we can scale up/down the recipe quantities.
  $node->recipe_custom_yield = $yield;

  // Remove the yield buttons.
  $node->recipe_show_yield_form = FALSE;

  // you should not be able to export unpublished recipes
  if ( $node->status == 0 ) {
    drupal_access_denied();
    return;
  }

  $build = node_view($node, 'print', $yield);
  // Don't pass to theme handlers.
  unset($build['#theme']);
  // Don't want to show links in print view.
  unset($build['links']);
  // Pass a fully rendered variable.  This is modeled after the book module in core.
  $node->rendered = drupal_render($build);

  return theme('recipe_export_html_page', array('node' => $node));
}


/**
 * Implementation of hook_theme().
 */
function recipe_html_theme() {
  return array(
    'recipe_export_html_page' => array(
      'template' => 'recipe_html_node',
      'variables' => array('node' => NULL),
    ),
  );
}


function template_preprocess_recipe_export_html_page(&$variables) {
  // Add recipe.css file since we are bypassing the normal page rendering routinee to get rid of sidebars and headers.
  $css_path = drupal_get_path("module", "recipe") . "/recipe.css";
  $variables['styles'] = '<style type="text/css" media="all">@import url("' . $css_path . '")</style>';

  $variables['title'] = check_plain($variables['node']->title);
  // 'contents' is already rendered.  Use the contents key so as not to confuse template authors.
  $variables['contents'] = $variables['node']->rendered;
}
